<?xml version="1.0" encoding="UTF-8"?>
<yml_catalog date="2026-01-26 16:20">
  <shop>
    <name>Demo Shop</name>
    <company>Demo Sneakers Shop</company>
    <url>https://sneakersdemoshop.com</url>
    <categories>
      <category id="sneakers_men">Мужские кроссовки</category>
      <category id="sneakers_women">Женские кроссовки</category>
      <category id="nike">Nike</category>
      <category id="jordan">Jordan</category>
      <category id="new_balance">New Balance</category>
      <category id="adidas">adidas</category>
    </categories>

    <offers>

      <!-- Products -->
      <offer id="product1" available="true">
        <url>https://demoshop.com/krossovki-nike-airdorce107</url>
        <price>19999</price>
        <currencyId>RUB</currencyId>
        <categoryId>sneakers_women</categoryId>
        <categoryId>nike</categoryId>
        <name>Nike Женские кроссовки Air Force 1 '07</name>
        <vendor>Nike</vendor>
        <balance>192</balance>
        <param name="product_collection">Air Force 1</param>
        <param name="product_gender">Женщины</param>
        <param name="product_rate">4,8</param>
      </offer>

      <!-- SKUs -->
      <offer id="sku1_1" group_id="product1" available="true">
        <name>Женские кроссовки Nike Air Force 1 '07 White</name>
        <url>https://demoshop.com/krossovki-nike-airdorce107</url>
        <picture>https://hofstadterp0.github.io/demoshop/img/nike_air_force_1_07w/product1.png</picture>
        <price>19999</price>
        <currencyId>RUB</currencyId>
        <categoryId>sneakers_women</categoryId>
        <categoryId>nike</categoryId>
        <vendor>Nike</vendor>
        <amount>92</amount>
        <param name="sku_collection">Air Force 1</param>
        <param name="sku_gender">Женщины</param>
        <param name="sku_rate">4,8</param>
      </offer>

      <offer id="sku1_2" group_id="product1" available="true">
        <name>Женские кроссовки Nike Air Force 1 '07 Pink</name>
        <url>https://demoshop.com/krossovki-nike-airdorce107</url>
        <picture>https://hofstadterp0.github.io/demoshop/img/nike_air_force_1_07w/sku1_1.png</picture>
        <price>19999</price>
        <currencyId>RUB</currencyId>
        <categoryId>sneakers_women</categoryId>
        <categoryId>nike</categoryId>
        <vendor>Nike</vendor>
        <param name="sku_collection">Air Force 1</param>
        <param name="sku_gender">Женщины</param>
        <param name="sku_rate">4,8</param>
      </offer>

    <offer id="sku1_3" group_id="product1" available="true">
        <name>Nike Женские кроссовки Air Force 1 '07 Light Blue</name>
        <url>https://demoshop.com/krossovki-nike-airdorce107</url>
        <price>15999</price>
        <currencyId>RUB</currencyId>
        <categoryId>sneakers_women</categoryId>
        <categoryId>nike</categoryId>
        <vendor>Nike</vendor>
        <picture>https://hofstadterp0.github.io/demoshop/img/nike_air_force_1_07w/sku1_2.png</picture>
        <param name="sku_collection">Air Force 1</param>
        <param name="sku_gender">Женщины</param>
        <param name="sku_rate">4,8</param>
      </offer>
    </offers>
  </shop>
</yml_catalog>



